### ISSUE TITLE
Python version check doesn't check

### ISSUE THREAD

**Issue by calroc** [michael-lazar/jetforce#19]
I accidentally ran jetforce with an older version of Python 3 and got a SyntaxError rather than the intended warning message.

```
Gemini$ git clone https://github.com/michael-lazar/jetforce.git
Cloning into 'jetforce'...
<snip>

Gemini$ cd jetforce/

Gemini/jetforce$ python3 jetforce.py
  File "jetforce.py", line 73
    """
      ^
SyntaxError: invalid syntax
```

**Comment by calroc** [comment]
Python 3.5.2 is the version I used.

**Comment by michael-lazar** [comment]
Hi, thanks for reporting the issue!

Unfortunately I don't think there's anything that can be done about this. Python will validate the whole file syntax before it executes any of the code, including the line that I put in there to check the version. Python 3.5 treats f-strings as a syntax error.

The version guard is kind of a last defense anyway. The intention was that it's better to fail fast and hard, instead of appearing like the server is working normally and then getting an exception later on during runtime. In this respect, the syntax error also accomplishes this goal.

**Comment by calroc** [comment]
Yeah, I just opened the ticket to let you know.  I can't think of anything to do about it either.  Nice code BTW!
