### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by makew0rld** [michael-lazar/jetforce#25]
I asked some questions about licensing [here](https://github.com/michael-lazar/jetforce/commit/1066d39125a8bff334c63fe3abc50fc3f45fb837) and it never got answered. Do you think you could take the time to answer them? I appreciate the work you've done with Jetforce, thank you for writing it. I just want to understand some of the things you said.

**Comment by michael-lazar** [comment]
I understand you have questions and I don't blame you for asking them. However, I don't think GitHub is a good forum to discuss topics like this because of the tendency for people not involved in the project to jump in and start dogpiling.  I would like to take some time to organize my thoughts around this and perhaps write a gemlog post about why I chose this particular license for this project.

**Comment by makeworld-the-better-one** [comment]
Ok, I understand. Thanks for replying, I'll wait for your post.
