### ISSUE TITLE
Does v0.3.2 change CGI? 

### ISSUE THREAD

**Issue by makeworld-the-better-one** [michael-lazar/jetforce#30]
Will CGI variables like `QUERY_STRING` now be decoded for you? If so, that could break existing apps and I think would be not with the RFC.

**Comment by michael-lazar** [comment]
``GEMINI_URL`` and ``QUERY_STRING`` remain the same as they were before, with the `%`-style URL encoding in the CGI variables.

``GEMINI_URL`` is a custom variable which is not defined in the RFC. But I think it makes the most sense to continue to use the "raw" URL string value that the client requested and not try to mess with decoding it.

``SCRIPT_NAME`` and ``PATH_INFO`` will now be decoded. This actually matches the RFC 3875 spec so I consider it a bug that they weren't decoded before.

> The SCRIPT_NAME variable MUST be set to a URI path (not URL-encoded)
   which could identify the CGI script (rather than the script's
   output).  The syntax is the same as for PATH_INFO (section 4.1.5)

> The PATH_INFO variable specifies a path to be interpreted by the CGI
   script.  It identifies the resource or sub-resource to be returned by
   the CGI script, and is derived from the portion of the URI path
   hierarchy following the part that identifies the script itself.
   Unlike a URI path, the PATH_INFO is not URL-encoded, and cannot
   contain path-segment parameters.  A PATH_INFO of "/" represents a
   single void path segment.

**Comment by makeworld-the-better-one** [comment]
Alright, good to know thanks!
